### PR TITLE
Update the evmc version and use evmone instead of aleth-interpreter

### PR DESCRIPTION
**Pull request by samlior**
1. Update the evmc version to 9.0.0(18bea41)
     + Add `access_storage` and `access_account` function for `evmc_host_interface`
     + Add `chain_id` and `block_base_fee` for `evmc_tx_context`
     + Add some `EvmcRevision` and `EvmcStatusCode` enum
     + Add `EvmcAccessStatus`
2. Use evmone 0.8.2(d2de6b1) instead of aleth-interpreter, because aleth-interpreter is no longer maintained
3. Fix some bugs
     + Add initialization for uint64_t array
     + Add `memcpy input_buffer` on `evmc_execute_evm`

### CODE REVIEW

**Comment by samlior** [comment]
I updated the scripts in `package.json`. The old script installs dependencies through `git submodule update --init --recursive`, but if you install this package through npm, there will be some problems, so I used `git clone --recursive xxx`.

I don’t make sure this is the best solution.

**Comment by no2chem** [comment]
Hm, interesting! Thanks for the PR. I'll try to take a look at this while I have a chance. BTW, what's your current use case for evmc-js?

**Comment by samlior** [comment]
We are developing a pure nodejs blockchain project which contains an evm. Currently, we use `@ethereumjs/vm`, but pure nodejs implementation has performance problems. It takes almost 50 ± 20ms to execute a transaction which used 28700 Gas. `evmone` and `evmc` takes almost 5ms to execute  a same transaction. And now, we are trying to replace `@ethereumjs/vm` with `evmone`.

I found this great project in GitHub, which saved me a lot of time. Thanks very much.

Hope for you review advise :)

**Comment by samlior** [comment]
New fix:
 + fix read `createAddress` from `evmc_result` on `completer_js`
 + add release logic for `evmc_result` on `completer_js`

**Pull request closed without merging**
